### ISSUE TITLE
Mixed usage of Tab and space

### ISSUE THREAD

**Issue by yepw** [TAMS-Group/robotiq#7]
Hi, thank you for upgrading the package to Ros noetic. It works perfectly with our gripper.

The only small thing is that my python interpreter complained about mixed usage of tab and space in robotiq_2f_gripper_control/src/robotiq_2f_gripper_control/baseRobotiq2FGripper.py.

It will be great if you can fix it.

https://github.com/TAMS-Group/robotiq/blob/a729fb6b85605424274c4c255785bee926735b7b/robotiq_2f_gripper_control/src/robotiq_2f_gripper_control/baseRobotiq2FGripper.py#L58-L84

**Comment by lianghongzhuo** [comment]
Hi, Thank you for your feedback, I hope this commit fixes your problem. 6d0d7474ab2b3ce9661c64f3b6f64551e7d24e98

**Comment by lianghongzhuo** [comment]
close in favor of 6d0d747
